using ExpeditionsMacro.Core.Models;

namespace ExpeditionsMacro.Automation.Diagnostics;

internal sealed record DeepDebugSanitizedSettings(
    int SchemaVersion,
    AppTheme Theme,
    string SelectedPresetId,
    string SelectedChallengePresetId,
    string SelectedStoryPresetId,
    string SelectedRaidPresetId,
    string SelectedMacroPlanId,
    bool AutoCaptureOnMacroError,
    bool IncludeLogsInDiagnosticArchives,
    bool DeepDebugEnabled,
    bool DebugModeEnabled,
    bool ManualInputRecordingEnabled,
    bool AutoCheckUiScaleOnStart,
    bool AutoCheckGameSettingsOnStart,
    bool MinimizeDuringAutomation,
    bool RestartRobloxWithPrivateServer,
    bool RestartRobloxAtMacroStart,
    bool PrivateServerLinkConfigured,
    int MacroHotkeyVirtualKey,
    int ShiftLockVirtualKey,
    int QuickPlacementVirtualKey,
    string PlayMenuKey,
    string UnitMenuKey,
    string AreasMenuKey,
    string CancelPlacementKey,
    string ChangeUnitTargetingKey,
    string UpgradeUnitKey,
    string SellUnitKey,
    string AutoUpgradeUnitKey,
    string ToggleAutoUpgradePlacedUnitsKey,
    ResourceRefuelDebugSettings ResourceRefuelDebug)
{
    public static DeepDebugSanitizedSettings From(
        AppSettings settings) => new(
        settings.SchemaVersion,
        settings.Theme,
        settings.SelectedPresetId,
        settings.SelectedChallengePresetId,
        settings.SelectedStoryPresetId,
        settings.SelectedRaidPresetId,
        settings.SelectedMacroPlanId,
        settings.AutoCaptureOnMacroError,
        settings.IncludeLogsInDiagnosticArchives,
        settings.DeepDebugEnabled,
        settings.DebugModeEnabled,
        settings.ManualInputRecordingEnabled,
        settings.AutoCheckUiScaleOnStart,
        settings.AutoCheckGameSettingsOnStart,
        settings.MinimizeDuringAutomation,
        settings.RestartRobloxWithPrivateServer,
        settings.RestartRobloxAtMacroStart,
        !string.IsNullOrWhiteSpace(
            settings.EncryptedPrivateServerLink),
        settings.MacroHotkeyVirtualKey,
        settings.ShiftLockVirtualKey,
        settings.QuickPlacementVirtualKey,
        settings.PlayMenuKey,
        settings.UnitMenuKey,
        settings.AreasMenuKey,
        settings.CancelPlacementKey,
        settings.ChangeUnitTargetingKey,
        settings.UpgradeUnitKey,
        settings.SellUnitKey,
        settings.AutoUpgradeUnitKey,
        settings.ToggleAutoUpgradePlacedUnitsKey,
        settings.ResourceRefuelDebug);
}
